title: Shanlin Ke
logo: blob/main/Shanlin_Ke.jpeg
description: Postdoc Research Fellow, 181 Longwood Ave, Boston, MA. 
email: spske@channing.harvard.edu
show_downloads: true
theme: jekyll-theme-architect
#jekyll-theme-minimal
