title: Shanlin Ke
logo: https://github.com/ShanlinKe/ShanlinKe.github.io/blob/main/Shanlin_Ke.jpeg
description: Postdoc Research Fellow, 181 Longwood Ave, Boston, MA. 
email: spske@channing.harvard.edu
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#jekyll-theme-minimal
