title: Shanlin Ke
logo: [Shanlin_Ke](https://github.com/ShanlinKe/ShanlinKe.github.io/assets/83370369/70403813-798d-4faa-814f-35795642a8a8)
description: Postdoc Research Fellow, 181 Longwood Ave, Boston, MA. 
email: spske@channing.harvard.edu
show_downloads: true
theme: jekyll-theme-architect
#jekyll-theme-minimal
